include ~/.cache/wal/colors-kitty.conf
font_size 15.0
background_opacity        0.7
remember_window_size  yes
initial_window_width  1240
initial_window_height 800 
window_padding_width 10
font_features JetBrains MonoSpace Nerd Font +zero +onum

font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

