# ### Hyprland ###
# Apps
$terminal = foot
$browser = zen-browser
$editor = codium
$fileExplorer = thunar

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 10
$windowGapsIn = 10
$windowGapsOut = 10
$singleWindowGapsOut = 10

# Window styling
$windowOpacity = 0.95
$windowRounding = 10

$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5 # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ##j
# Workspaces
$kbMoveWinToWs = Alt+Ctrl
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Alt
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Alt, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Alt, Z
$kbResizeWindow = Alt, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Alt, V
$kbCloseWindow = Alt, Q

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Alt, T
$kbBrowser = Alt, W
$kbEditor = Alt, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
